src/main/java/decodex/data/Data.java, src/test/java/decodex/DecodexTest.java, src/test/java/decodex/data/DataTest.java
=> Add Data Class

src/main/java/decodex/modules/BaseModule.java
=> Add abstract BaseModule Class

src/main/java/decodex/data/DataManager.java, src/test/java/decodex/data/DataManagerTest.java
=> Add DataManager Class

src/main/java/decodex/Decodex.java, src/main/java/decodex/data/exception/ParserException.java, src/main/java/decodex/parser/Parser.java, src/test/java/decodex/parser/ParserTest.java
=> Moved ParserException into decodex.data.exception package.

src/main/java/decodex/Decodex.java, src/main/java/decodex/commands/Command.java, src/main/java/decodex/commands/SelectCommand.java, src/main/java/decodex/data/exception/ModuleException.java, src/main/java/decodex/data/exception/ParserException.java, src/main/java/decodex/modules/BaseModule.java, src/main/java/decodex/modules/base64/Base64Decoder.java, src/main/java/decodex/modules/base64/Base64Encoder.java, src/main/java/decodex/parser/Parser.java, src/test/java/decodex/commands/DataCommandTest.java, src/test/java/decodex/commands/ResetCommandTest.java, src/test/java/decodex/commands/SelectCommandTest.java, src/test/java/decodex/modules/base64/Base64DecoderTest.java, src/test/java/decodex/parser/ParserTest.java, text-ui-test/EXPECTED.TXT, text-ui-test/input.txt
Fixes #13 #14 #56 #70 #71 
Other changes
1. Changed the base64 description
2. Added more Parser JUnit test for ParserTest.
3. Changed the Text-ui-test's expect.txt
4. Removed and reorganized some unused imports (those that I modified)
=> Add changes to Parser and Decodex

src/main/java/decodex/data/Data.java
=> Add assertion to ensure data is not null in `Data` constructor

docs/AboutUs.md
=> Add dimensions to profile pictures

src/main/java/decodex/data/DataManager.java, src/main/java/decodex/parser/Parser.java
=> Change JavaDocs for 2 class as a sample to standardize

docs/DeveloperGuide.md
=> DG - Before writing code portion

docs/UserGuide.md, src/main/java/decodex/modules/ModuleManager.java, src/main/java/decodex/ui/messages/ErrorMessages.java
=> Fix `rotencode` parameter

docs/UserGuide.md
=> Add recipeName clarification

docs/UserGuide.md
=> Add explanation on separators in data

src/main/java/decodex/modules/binary/BinaryDecoder.java, src/main/java/decodex/modules/binary/BinaryEncoder.java, src/main/java/decodex/modules/hex/HexDecoder.java, src/main/java/decodex/modules/hex/HexEncoder.java, src/main/java/decodex/modules/rot/RotEncoder.java, text-ui-test/EXPECTED.TXT
=> Update module description to follow UG

src/main/java/decodex/parser/Parser.java, src/main/java/decodex/parser/RecipeCommandParser.java, src/main/java/decodex/ui/messages/ErrorMessages.java
=> Fix command argument issues

src/main/java/decodex/commands/InputCommand.java, src/main/java/decodex/commands/recipe/RecipePopCommand.java, src/main/java/decodex/commands/recipe/RecipePushCommand.java, src/main/java/decodex/commands/recipe/RecipeResetCommand.java, src/main/java/decodex/commands/recipe/RecipeSelectCommand.java, src/main/java/decodex/modules/Module.java
* Compress method signatures of commands to less lines
=> Remove dead getDescription of Module.java

src/main/java/decodex/Decodex.java, src/main/java/decodex/commands/ShowCommand.java, src/main/java/decodex/modules/base64/Base64Decoder.java, src/main/java/decodex/modules/base64/Base64Encoder.java, src/main/java/decodex/parser/Parser.java, src/main/java/decodex/storage/Storage.java
Fixes issues raised by TA 
Fixes #215
=> Refactor, Code quality and JavaDocs for `Storage`, `Decodex`, `Parser`

src/main/java/decodex/modules/rot/RotEncoder.java, src/main/java/decodex/recipes/RecipeManager.java
* Convert comments for class members to single line
Fixes #216
=> Refactor RotEncoder

src/main/java/decodex/modules/hex/HexDecoder.java
=> Simplify HexDecode

docs/UserGuide.md
* Add hyperlinks for recipe commands
* Fix grammar
* Update section headers to match notion
=> Add UG hyperlinks

docs/DeveloperGuide.md
* Update and move TOC to top
* Update introduction, purpose and usage
* Fix Terminologies and Symbols header indentation
* Update terminologies
* Add note before Design section
* Add manual testing sub sections
=> Partial Update for DG V2.1
